# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 2.1.0-rc.0
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly (Nightly)
PackageUrl: https://docs.butterfly.linwood.dev
License: AGPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Moniker: butterfly-nightly
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Add image background svg support
  - Add triangle to shape tool and add dialog (#664)
  - Add name field to create template dialog
  - Add button to invert selection in templates dialog
  - Add option to override tools for selected templates (#613)
  - Add intents to open zip, pdf and images with this app on android
  - Redesign templates dialog
  - Fix linux metainfo again
  - Fix label is not being created when unfocussing
  - Fix area preview rendering
  - Fix recent history not removed when deleting the document
  - Fix editable input not being updated
  - Fix baking when using smooth navigation
  - Fix locale displayed as system language if there is no translation for this
  - Fix missing translations for locales
  - Fix render background gets ignored (#670)
  - Remove old unused code
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.1.0-rc.0
ManifestType: defaultLocale
ManifestVersion: 1.5.0
