# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 2.2.3-rc.0
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly (Nightly)
PackageUrl: https://docs.butterfly.linwood.dev
License: AGPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Moniker: butterfly-nightly
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Add toggle for color toolbar (#611)
  - Add save button indicator for autosave (#757)
  - Add duplicate layer button
  - Add tool options panel position
  - Add path laser animation
  - Separate laser duration in normal duration and hide duration
  - Use long press to move tools on all platforms to improve desktop touch behavior
  - Use sha checksum for assets
  - Update dropdown buttons in shape and constraints to material 3
  - Separate personalization settings in new view settings
  - Fix webdav on windows
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.2.3-rc.0
ManifestType: defaultLocale
ManifestVersion: 1.5.0
