# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly
PackageVersion: 2.1.1-rc.1
InstallerType: inno
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2024-05-21
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/LinwoodDev/Butterfly/releases/download/v2.1.1-rc.1/linwood-butterfly-windows-setup-x86_64.exe
  InstallerSha256: a454cba6f6cbf393b5f49cd8a2fddda583630309e5a8973cdf98173fd8d1ae5b
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/LinwoodDev/Butterfly/releases/download/v2.1.1-rc.1/linwood-butterfly-windows-setup-x86_64.exe
  InstallerSha256: a454cba6f6cbf393b5f49cd8a2fddda583630309e5a8973cdf98173fd8d1ae5b
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
