# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly
PackageVersion: 2.1.1-rc.1
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly
PackageUrl: https://docs.butterfly.linwood.dev
License: GPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Add hide cursor while drawing
  - Improve pdf import performance (#702)
  - Reimplement quality in pdf import (#702)
  - Center grid items in home page
  - Modernize home page header gradient to use secondary and primary color
  - Improve webdav requests (#703)
  - Improve image quality (#704)
  - Improve baked image quality
  - Improve responsiveness
  - Improve path eraser performance
  - Use a blue/gray for secondary color in classic theme
  - Fix launching url does nothing
  - Fix settings on mobile fill full height
  - Fix grid switch on file view will be shown in navigator
  - Fix missing scrollbar in home page
  - Fix scale proportional not working
  - Fix bfly file import and export on android (#709)
  - Fix old baked image not being disposed
  - Fix toolbar not showing on desktop in toolbar position inline
  - Fix removing elements hides all elements for a moment
  - Fix label could not be edited (#712)
  - Upgrade to flutter 3.22
  - Fix linux screenshot appdata
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.1.1-rc.1
ManifestType: defaultLocale
ManifestVersion: 1.5.0
