# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 2.0.0-rc.2
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly (Nightly)
PackageUrl: https://docs.butterfly.linwood.dev
License: AGPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Moniker: butterfly-nightly
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Improve button of display icons (#549)
  - Improve performance when saving (#547)
  - Improve mobile add dialog
  - Improve selected icons in settings
  - Improve consistency of close button (#550)
  - Rename default locale to system locale
  - Fix asset plus button (#550)
  - Fix calling onScale to tools on moving on touch devices (#546)
  - Fix exporting documents as png or svg
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.0.0-rc.2
ManifestType: defaultLocale
ManifestVersion: 1.5.0
