# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly
PackageVersion: 2.1.0-rc.3
InstallerType: inno
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2024-05-07
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/LinwoodDev/Butterfly/releases/download/v2.1.0-rc.3/linwood-butterfly-windows-setup-x86_64.exe
  InstallerSha256: 9B947B7797210DDD63D33EAFAA3513E2F549DCD12721F909A76E18FA26BAC680
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/LinwoodDev/Butterfly/releases/download/v2.1.0-rc.3/linwood-butterfly-windows-setup-x86_64.exe
  InstallerSha256: 9B947B7797210DDD63D33EAFAA3513E2F549DCD12721F909A76E18FA26BAC680
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
