# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 2.2.1-rc.0
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly (Nightly)
PackageUrl: https://docs.butterfly.linwood.dev
License: AGPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Moniker: butterfly-nightly
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Add convert to layer to collection dialog
  - Readd option to select custom collection
  - Update button in name dialog to context specific action
  - Use live icon in add dialog (for example on undo, redo and full screen tools)
  - Improve layout of collection dialog
  - Improve copy to clipboard snackbar to show color
  - Change sensitivity settings to percent
  - Change min sensitivity of inputs to 10%
  - Rename context menu item name to rename in area context menu
  - Use search bar in areas navigator instead of normal text field
  - Fix select sensitivity slider in input settings changes scroll sensitivity
  - Fix current collection not being shown in collection dialog
  - Fix duplicating not working correctly
  - Fix layer rendering
  - Fix convert to layer not working before reopening the app
  - Fix file name only supports latin characters (#743)
  - Fix selection not updated when elements changed
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.2.1-rc.0
ManifestType: defaultLocale
ManifestVersion: 1.5.0
