# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 2.2.1-rc.1
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly (Nightly)
PackageUrl: https://docs.butterfly.linwood.dev
License: AGPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Moniker: butterfly-nightly
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Add bit mapping of buttons in pointer test
  - Add autofocus to add dialog search bar
  - Add transition when opening add dialog
  - Add size transition to toolbar
  - Improve search and settings dialog transition
  - Change color toolbar to not have the full width
  - Fix pasting with label tool replaces text instead of appending
  - Fix unstable sort algorithm if layer is the same
  - Fix switching data directory not working
  - Fix input button mapping not working on multiple button presses (#748)
  - Fix app link in android
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.2.1-rc.1
ManifestType: defaultLocale
ManifestVersion: 1.5.0
