# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly
PackageVersion: 2.1.1-rc.0
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly
PackageUrl: https://docs.butterfly.linwood.dev
License: GPL-3.0
LicenseUrl: https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Make dav requests more performant (#689)
  - Add icons to platform theme setting
  - Enhance mobile home page
  - Change lasso select icon to a real lasso
  - Fix visible layers are not working correctly (#692)
  - Fix remote button if external storage is default
  - Fix linux metainfo
  - Fix image operations
  - Fix no element on fetch in dav requests (#695)
  - Fix context buttons in template dialog closes the dialog
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.1.1-rc.0
ManifestType: defaultLocale
ManifestVersion: 1.5.0
